// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vleopegtuhrjenletylm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsZW9wZWd0dWhyamVubGV0eWxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU4NTI3OTEsImV4cCI6MjA5MTQyODc5MX0.iVX4Sj3ZQvwWJX6fFnG7eoESbeW5JCd4oNklaA-g2wE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});